name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: dev
    - name: Build project
      run: npm run build
    - name: Deploy to prod
      uses: actions/checkout@v2
      with:
        ref: prod
        path: prod-deploy
      run: |
        mv dist/* prod-deploy/
        cd prod-deploy
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add .
        git commit -m "Deploy to prod"
        git push
